package com.miguelaetxio.mimoo.data.remote.dto

/**
 * Manifiesto de versión publicado junto al APK en cada Release de
 * AndroidReleases (H07 PARTE 2, PASO 2.2 -- generado por
 * build-and-deploy.yml, no por esta app). Los nombres de campo deben
 * coincidir exactamente con el JSON real -- ver el paso "Generar
 * manifest.json de version" del workflow.
 * ---
 * Version manifest published alongside the APK in every
 * AndroidReleases Release (H07 PART 2, STEP 2.2 -- generated by
 * build-and-deploy.yml, not by this app). Field names must match the
 * real JSON exactly -- see the "Generar manifest.json de version"
 * step of the workflow.
 */
data class UpdateManifest(
    val versionCode: Int,
    val versionName: String,
    val apkUrl: String,
)
