package com.miguelaetxio.mimoo.data.backup

import android.content.Context
import android.util.Log
import androidx.documentfile.provider.DocumentFile
import androidx.room.withTransaction
import com.miguelaetxio.mimoo.data.download.StorageManager
import com.miguelaetxio.mimoo.data.local.AppDatabase
import com.miguelaetxio.mimoo.data.local.dao.FavoriteAlbumDao
import com.miguelaetxio.mimoo.data.local.dao.PlaylistDao
import com.miguelaetxio.mimoo.data.local.dao.SearchResultTrackDao
import com.miguelaetxio.mimoo.data.local.entity.DownloadStatus
import com.miguelaetxio.mimoo.data.local.entity.FavoriteAlbum
import com.miguelaetxio.mimoo.data.local.entity.Playlist
import com.miguelaetxio.mimoo.data.local.entity.PlaylistTrackCrossRef
import com.miguelaetxio.mimoo.data.local.entity.SearchResultTrack
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

private const val TAG = "MiMoo-Backup-Import"

/** Resultado de una importación, para que la UI (PASO 4) muestre un resumen. */
data class BackupImportResult(
    val importedTracks: List<SearchResultTrack>,
    val favoriteAlbumCount: Int,
    val playlistCount: Int,
)

/**
 * Ejecuta la sustitución destructiva del repositorio completo (H06
 * PASO 4, decisión de Miguel Ángel: el repositorio destino MUERE y se
 * sustituye por la copia importada -- sin fusión). Vive fuera de los
 * repositorios normales de `data/local/repository` porque cruza
 * varios DAOs dentro de una única transacción Room
 * (`AppDatabase.withTransaction`), algo que ningún repositorio
 * individual hace hoy.
 * ---
 * Runs the destructive substitution of the whole repository (H06
 * PASO 4, Miguel Ángel's decision: the destination repository DIES
 * and gets replaced by the imported copy -- no merge). Lives outside
 * the normal `data/local/repository` repositories because it spans
 * several DAOs inside a single Room transaction
 * (`AppDatabase.withTransaction`), something no individual repository
 * does today.
 */
@Singleton
class BackupImportRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val database: AppDatabase,
    private val trackDao: SearchResultTrackDao,
    private val favoriteAlbumDao: FavoriteAlbumDao,
    private val playlistDao: PlaylistDao,
    private val storageManager: StorageManager,
) {
    /**
     * 1) Borra los archivos de audio físicos existentes en la raíz
     * SAF (si hay una elegida) -- si no se hiciera, quedarían
     * huérfanos en disco sin fila en Room, y una reconciliación
     * futura (LibraryReconciler) los recrearía como filas sintéticas
     * SIN los metadatos importados, contradiciendo el propósito del
     * hito (ver ANNEX_H06.md PASO 4).
     * 2) Transacción Room: borra las 4 tablas y reinserta desde
     * `bundle`, con `filePath = null` / `downloadStatus = PENDING` /
     * `downloadProgress = 0` en cada pista (se redescargan todas,
     * PASO 5), y las playlists con id autogenerado nuevo (nunca
     * `originalId`).
     * ---
     * 1) Deletes existing physical audio files under the SAF root (if
     * one was chosen) -- otherwise they'd be left orphaned on disk
     * with no Room row, and a future reconciliation (LibraryReconciler)
     * would recreate them as synthetic rows WITHOUT the imported
     * metadata, defeating the hito's purpose (see ANNEX_H06.md
     * PASO 4).
     * 2) Room transaction: deletes the 4 tables and reinserts from
     * `bundle`, with `filePath = null` / `downloadStatus = PENDING` /
     * `downloadProgress = 0` on every track (all get re-downloaded,
     * PASO 5), and playlists with a fresh autogenerated id (never
     * `originalId`).
     */
    suspend fun importDestructively(bundle: BackupBundle): BackupImportResult =
        withContext(Dispatchers.IO) {
            Log.d(TAG, "importDestructively() -- borrando archivos físicos existentes...")
            deleteExistingPhysicalFiles()
            Log.d(TAG, "importDestructively() -- archivos físicos borrados. Iniciando transacción Room...")

            lateinit var result: BackupImportResult
            database.withTransaction {
                playlistDao.deleteAllCrossRefs()
                playlistDao.deleteAllPlaylists()
                favoriteAlbumDao.deleteAll()
                trackDao.deleteAll()
                Log.d(TAG, "importDestructively() -- 4 tablas borradas. Insertando ${bundle.tracks.size} pistas...")

                val newTracks = bundle.tracks.map { it.toEntity() }
                trackDao.insertAll(newTracks)

                bundle.favoriteAlbums.forEach { dto ->
                    favoriteAlbumDao.insert(FavoriteAlbum(artist = dto.artist, album = dto.album))
                }

                bundle.playlists.forEach { playlistDto ->
                    val newPlaylistId = playlistDao.insertPlaylist(
                        Playlist(name = playlistDto.name, createdAt = playlistDto.createdAt)
                    )
                    playlistDto.trackYoutubeIdsInOrder.forEachIndexed { index, youtubeId ->
                        playlistDao.addTrackToPlaylist(
                            PlaylistTrackCrossRef(
                                playlistId = newPlaylistId,
                                youtubeId = youtubeId,
                                position = index,
                            )
                        )
                    }
                }

                result = BackupImportResult(
                    importedTracks = newTracks,
                    favoriteAlbumCount = bundle.favoriteAlbums.size,
                    playlistCount = bundle.playlists.size,
                )
                Log.d(
                    TAG,
                    "importDestructively() -- transacción completa: ${newTracks.size} pistas, " +
                        "${bundle.favoriteAlbums.size} favoritos, ${bundle.playlists.size} playlists"
                )
            }
            result
        }

    /**
     * Borra el CONTENIDO de la raíz SAF (no la raíz en sí -- solo sus
     * hijos). Si todavía no hay raíz elegida (`hasRootUri() ==
     * false`), no hay nada que borrar -- el primer inicio de la app
     * tras instalar limpio pedirá la carpeta como siempre.
     *
     * Recursión explícita, no una sola llamada a `delete()` sobre
     * cada hijo: no todos los proveedores SAF garantizan borrar un
     * subárbol de carpetas no vacío de una sola vez, así que se vacía
     * cada carpeta primero y solo entonces se borra ella misma --
     * mismo principio de cautela que `LibraryReconciler.pruneEmptyFolders`.
     */
    private fun deleteExistingPhysicalFiles() {
        val rootUri = storageManager.getRootUri()
        if (rootUri == null) {
            Log.d(TAG, "deleteExistingPhysicalFiles() -- sin raíz SAF elegida todavía, nada que borrar")
            return
        }
        val root = DocumentFile.fromTreeUri(context, rootUri)
        if (root == null) {
            Log.w(TAG, "deleteExistingPhysicalFiles() -- DocumentFile.fromTreeUri devolvió null para $rootUri")
            return
        }
        val children = root.listFiles()
        Log.d(TAG, "deleteExistingPhysicalFiles() -- borrando ${children.size} elementos bajo la raíz")
        children.forEach { child -> deleteRecursively(child) }
    }

    private fun deleteRecursively(doc: DocumentFile) {
        if (doc.isDirectory) {
            doc.listFiles().forEach { child -> deleteRecursively(child) }
        }
        doc.delete()
    }
}

private fun TrackBackupDto.toEntity(): SearchResultTrack = SearchResultTrack(
    youtubeId = youtubeId,
    title = title,
    channelTitle = channelTitle,
    durationSeconds = durationSeconds,
    thumbnailUrl = thumbnailUrl,
    filePath = null,
    downloadStatus = DownloadStatus.PENDING,
    downloadProgress = 0,
    artist = artist,
    album = album,
    isFavorite = isFavorite,
    coverArtUrl = coverArtUrl,
    trackPosition = trackPosition,
    sourceUrl = sourceUrl,
)
