package com.miguelaetxio.mimoo.data.backup

import com.miguelaetxio.mimoo.data.local.entity.FavoriteAlbum
import com.miguelaetxio.mimoo.data.local.entity.SearchResultTrack

/**
 * Formato de archivo de exportación/importación del repositorio
 * completo (H06). Deliberadamente independiente de las entidades
 * Room reales (SearchResultTrack, FavoriteAlbum, Playlist,
 * PlaylistTrackCrossRef) para que el formato de archivo no quede
 * acoplado al esquema interno de la base de datos -- un cambio futuro
 * de esquema no debería romper la lectura de backups antiguos sin
 * más ceremonia que un salto de `version`.
 *
 * `version` empieza en 1. Cualquier cambio de forma incompatible
 * (campo eliminado/renombrado, semántica distinta) debe subir este
 * número; `BackupSerializer` rechaza con un mensaje claro cualquier
 * versión que no reconozca, en vez de intentar leerla a ciegas.
 * ---
 * File format for exporting/importing the whole repository (H06).
 * Deliberately independent from the real Room entities
 * (SearchResultTrack, FavoriteAlbum, Playlist,
 * PlaylistTrackCrossRef) so the file format isn't coupled to the
 * internal DB schema -- a future schema change shouldn't break
 * reading old backups beyond bumping `version`.
 *
 * `version` starts at 1. Any incompatible shape change (removed/
 * renamed field, different semantics) must bump this number;
 * `BackupSerializer` rejects any version it doesn't recognize with a
 * clear message instead of silently trying to read it.
 */
data class BackupBundle(
    val version: Int = CURRENT_VERSION,
    val exportedAt: Long,
    val tracks: List<TrackBackupDto>,
    val favoriteAlbums: List<FavoriteAlbumBackupDto>,
    val playlists: List<PlaylistBackupDto>,
) {
    companion object {
        const val CURRENT_VERSION = 1
    }
}

/**
 * Una pista exportable. Deliberadamente SIN filePath/downloadStatus/
 * downloadProgress -- son específicos del dispositivo origen y se
 * reinicializan siempre en la importación (ver PASO 4 del anexo:
 * filePath = null, downloadStatus = PENDING, downloadProgress = 0).
 * youtubeId sí viaja -- es la clave real y estable, no depende del
 * dispositivo.
 * ---
 * An exportable track. Deliberately WITHOUT filePath/downloadStatus/
 * downloadProgress -- those are specific to the source device and
 * are always reset on import (see annex PASO 4: filePath = null,
 * downloadStatus = PENDING, downloadProgress = 0). youtubeId does
 * travel -- it's the real, stable key, device-independent.
 */
data class TrackBackupDto(
    val youtubeId: String,
    val title: String,
    val channelTitle: String,
    val durationSeconds: Int,
    val thumbnailUrl: String?,
    val artist: String?,
    val album: String?,
    val isFavorite: Boolean,
    val coverArtUrl: String?,
    val trackPosition: Int?,
    val sourceUrl: String?,
)

data class FavoriteAlbumBackupDto(
    val artist: String,
    val album: String,
)

/**
 * `originalId` es el id autogenerado de la Playlist en el
 * dispositivo origen -- se conserva solo para trazabilidad y para
 * que dos exports sucesivos del mismo dispositivo sean comparables;
 * la importación (PASO 4) NUNCA lo reutiliza como id real, siempre
 * inserta con id autogenerado nuevo en destino.
 *
 * `trackYoutubeIdsInOrder` aplana PlaylistTrackCrossRef dentro de la
 * propia playlist (orden real, por posición) en vez de exportar la
 * tabla de unión suelta -- simplifica el remapeo de ids en la
 * importación. Si la playlist contenía una pista sintética
 * (`local:...`), su id ya no aparece aquí -- BackupBuilder filtra las
 * pistas sintéticas de raíz, antes de construir esta lista (ver
 * SearchResultTrack.local: en TrackBackupDto/BackupBuilder).
 * ---
 * `originalId` is the Playlist's autogenerated id on the source
 * device -- kept only for traceability and so two successive exports
 * of the same device are comparable; import (PASO 4) NEVER reuses it
 * as a real id, it always inserts with a fresh autogenerated id on
 * the destination.
 *
 * `trackYoutubeIdsInOrder` flattens PlaylistTrackCrossRef inside the
 * playlist itself (real, position-based order) instead of exporting
 * the loose join table -- simplifies id remapping on import. If the
 * playlist contained a synthetic track (`local:...`), its id no
 * longer appears here -- BackupBuilder filters synthetic tracks at
 * the root, before building this list (see SearchResultTrack.local:
 * in TrackBackupDto/BackupBuilder).
 */
data class PlaylistBackupDto(
    val originalId: Long,
    val name: String,
    val createdAt: Long,
    val trackYoutubeIdsInOrder: List<String>,
)

/** Prefijo real de las filas sintéticas generadas por LibraryReconciler -- ver SearchResultTrack. */
private const val SYNTHETIC_TRACK_PREFIX = "local:"

/**
 * `true` si esta fila es sintética (generada por LibraryReconciler
 * para un archivo pegado a mano sin fila real, sin vídeo de YouTube
 * detrás). Decisión de Miguel Ángel (S006): estas filas nunca se
 * exportan.
 */
fun SearchResultTrack.isSyntheticLocalTrack(): Boolean =
    youtubeId.startsWith(SYNTHETIC_TRACK_PREFIX)

fun SearchResultTrack.toBackupDto(): TrackBackupDto = TrackBackupDto(
    youtubeId = youtubeId,
    title = title,
    channelTitle = channelTitle,
    durationSeconds = durationSeconds,
    thumbnailUrl = thumbnailUrl,
    artist = artist,
    album = album,
    isFavorite = isFavorite,
    coverArtUrl = coverArtUrl,
    trackPosition = trackPosition,
    sourceUrl = sourceUrl,
)

fun FavoriteAlbum.toBackupDto(): FavoriteAlbumBackupDto =
    FavoriteAlbumBackupDto(artist = artist, album = album)
